<?php

namespace App\Filament\Resources\Smtps\Pages;

use App\Filament\Resources\Smtps\SmtpResource;
use App\Models\Smtp;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;

class CreateSmtp extends CreateRecord
{
    protected static string $resource = SmtpResource::class;

    protected function handleRecordCreation(array $data): Model
    {
        $data['reference'] = Smtp::generateReference();
        return parent::handleRecordCreation($data); // TODO: Change the autogenerated stub
    }
}
